### ISSUE TITLE
Game crash invite friends button

### ISSUE THREAD

**Issue by Salads** [TurningWheel/Barony#1]
The game crashes if the steam servers are down and I click "Invite Friends" in the server lobby screen.

Using `SteamUser()->BLoggedOn` could possibly fix it

[buttonInviteFriends(button_t *my)](https://github.com/TurningWheel/Barony/blob/abf9a614088d8a1ba4669ae7290f5052a90a233b/src/menu.cpp#L4269-L4275)

**Comment by addictgamer** [comment]
Ah, hmm. I'll look into it.
Do you know if this happens *only* if the steam servers themselves are down, or can the issue be replicated if I would, say, disconnect my computer's internet access mid-game? Just for reproducability's sake.

**Comment by Salads** [comment]
I went ahead and disabled my network adapter, then pressed the "Invite Friends" button again and it crashed just like when the steam servers are down.

I also had a friend play with me and disabled my adapter while we were in the starting level, and there was no crash on either side, just normal disconnecting messages.

**Comment by addictgamer** [comment]
Awesome, that will help test. Thanks.

**Comment by addictgamer** [comment]
Fixed in a85195a
