### ISSUE TITLE
[2.0.5][Multiplayer][Client] Client will continue to see Host on fire after they step in water

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#102]
**ISSUE:**
When a Host is set on fire, other Clients can see an effect of sparks coming off of that player. When a Host is on fire and steps into water (starts swimming), both the effect of sparks and the status of being "On Fire" are removed. However, for the Clients, they continue to see that the Hosthas the spark effect.

**EXPECTED RESULT:**
When a player loses a status, such as being on fire, the effect corresponding to that status should also be removed.

**STEPS TO REPRODUCE:**
Requires water, so the Swamp is the testing ground.
1. In a multiplayer Steam game, have a method of lighting someone on fire, or being lit on fire, without dying. (Goblins with Fire rods work well).
2. Have the host be lit on fire, then submerge themselves in water. The effect will remain for players other than the host (verified with two clients).
3. Have a client be set on fire, then submerge themselves in water. (The effect is not visible on the clients #100 but normally, it would be removed).

**ADDITIONAL INFO:**
I haven't fully tested this one, and I will update this issue as necessary. I know for now this is an issue with clients, I believe I have been a host and watched a client submerge themselves and lose the spark effect, but I have not verified yet. I cannot remember if the effect persists while in water, or only after exiting.

It's very likely that similar to #100 the host sees the correct behavior, but every client does not.
I have been told that it eventually went out. I was also told that while I was invisible (cloak of invisibility), and not on fire anymore, the effect still lasted for a long time. It is very possible that this issue is actually:
**"On Fire" effect on another player does not disappear if it is removed before timing out (clients only)**

**Comment by crkellen** [comment]
Updating the title and OP of this, as through more testing, the issue has been narrowed down.
The Host does not send an update when they remove the fire from themselves when going into water.
A pull request will follow shortly.

**Comment by addictgamer** [comment]
Resolved in #203
