### ISSUE TITLE
[2.0.5][Windows][Multiplayer] Client has difficulties "bumping" another player

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#104]
**ISSUE:**
Players can "bump" each other by right clicking. This displays their name, current HP/Max, etc. Clients in a multiplayer game are often unable to preform this action, but the Host can freely.

**EXPECTED RESULT:**
When a Client player right-clicks another player, it should preform the "bump" action.

**STEPS TO REPRODUCE:**
1. Host a multiplayer game.
2. Invite or have friends join through Steam.
3. Start the game.
4. Right-click the other players, note any difficulties in doing so. The text should appear in the bottom right.
5. Have someone else Host a multiplayer game.
6. Join through Steam.
7. Start the game.
8. Attempt to right-click other players, note any difficulties in doing so. The text should appear in the bottom right.

**ADDITIONAL INFO:**
By the time we reached the underworld, the "bump" action was completely impossible for the Client with me to do. I could still do it freely. Often times he has to be slightly inside of my entity (pushing me), to get it to trigger.

**Comment by SheridanR** [comment]
I believe it always works for clients as long as you click on the player's head. It has nothing to do with proximity or collision.

The same issue occurs for talking to followers or shopkeepers. It only works for clients if you click on their head.

Clicking on limbs is supposed to do a lookup on the client to get the character's head uid, which iirc is the "actual" object-click that is sent to the server. But something along that pipeline isn't working right.

**Comment by crkellen** [comment]
Yep. @WALLOFJUSTICE explained that only the head exists, and everything else is simulated locally.
I'll take a look at it sometime.

**Comment by crkellen** [comment]
The issue with this was due to the Client being unable to select entities that were not the head.
This was because the entities were not in the 'map_entities' map that contains all entities.
This was fixed by changing a return to a continue statement.

**Comment by addictgamer** [comment]
Re-opening this since I want it merged into an off-shoot of master and shipped in a live build.

**Comment by crkellen** [comment]
As requested, there is now a new PR based on v2.0.7 branch.

**Comment by addictgamer** [comment]
Merged in #218 into v2.0.7-branch
