### ISSUE TITLE
New background colors for Unappraised/Blessed items very similar

### ISSUE THREAD

**Issue by daed** [TurningWheel/Barony#11]
First of all, I want to say how big of a fan I am of the background colors added to items.  It makes finding unappraised stuff in your inventory so much easier!

That being said, I can't really tell the difference between the background color on a blessed item vs that of an unidentified item.  I have colorblind mode on (yes, I'm colorblind) and it's still not helping.   Would it be possible for someone to turn the blessed color to something else, like a blue of some sort?

**Comment by Gilgatex** [comment]
I'll see what I can do.  I did not know there was a colorblind mode, so I didn't account for that when I coded it.

**Comment by daed** [comment]
Thanks for that.  

I just pulled the code down yesterday, so I'm not entirely sure where the colorblind mode is actually getting used, but I think it shows up in the config files as '/colorblind', if that helps you track it down.

**Comment by Gilgatex** [comment]
I'm just a volunteer coder, so unless it's a feature I use, I probably don't know about it :)

**Comment by addictgamer** [comment]
Changed colorblind mode to draw blessed items with a light blue background and text in 8e4d1708b06172733e9b98056ff784dc1782ab12
