### ISSUE TITLE
[2.0.5][Multiplayer][Client] Fountains do not stop animating for Client

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#114]
**ISSUE:**
When fountains are right-clicked, they get used, causing their animation to stop. This is not the case on Client players, who will always see the fountains animation.

**EXPECTED RESULT:**
When someone, Host or Client, uses a fountain, it should stop it's animation.

**STEPS TO REPRODUCE:**
1. Be a Client
2. Find a fountain
3. Drink from it, notice the animation does not stop.

**ADDITIONAL INFO:**
It does not matter who drinks from the fountain. It will always animate.

**Comment by addictgamer** [comment]
Resolved in #204
