### ISSUE TITLE
[2.0.5] When typing keyboard inputs still function

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#116]
**ISSUE:**
When a player, singleplayer or otherwise, presses enter and begins typing, all inputs are still valid. This means that when a player looks around, left or right clicks, or presses WASD, all functionality is still the same. However, when hitting WASD to move, they player does not move, but still animates, causing them to bounce slightly in place.

**EXPECTED RESULT:**
Player's keyboard inputs should be nullified/frozen for the duration of the chat window being open. So when WASD is pressed, the player does not animate in an attempt to move.

**STEPS TO REPRODUCE:**
1. Start a game.
2. Type in chat, press W, A, S, and D keys.

**ADDITIONAL INFO:**
A slight annoyance, it doesn't affect gameplay as far as I can tell, but should still be fixed.

**Comment by addictgamer** [comment]
Resolved in #206
