### ISSUE TITLE
[2.0.5][Multiplayer] There is no way to tell who is connected, or if someone has disconnected

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#117]
**ISSUE:**
When in a multiplayer game, there is no way of telling who is still connected. There is also no notification or way of knowing when a player disconnects.

***EDIT:*** It turns out that Clients receive a message in text when another Client disconnects, but the Host never receives these messages.
***EDIT2:*** Well it seems that actually, only Client 3 sends the message to Client 2. ~~I have not tested with four players yet.~~ The 2nd connected Client does not send a message to host or Client 3 on his disconnect. The 4th Client sends a message to both Client 2 and 3.
***EDIT3:*** Seemingly, Players only send messages to the players above them, excluding the host.
Player 3 sends no messages to Player 4. Same as Player 2. However, Player 4 will send messages to both Player 2 and 3.

**EXPECTED RESULT:**
Players should have some sort of way of seeing a list of currently connected players. Perhaps when pressing tab, their name, and maybe their status (alive/dead), should be listed. Additionally, a message should be sent when a Client disconnects, that notifies everyone that someone has left, this could be implemented in the same packet as #115. 

**STEPS TO REPRODUCE:**
1. Start a multiplayer game with multiple people.
2. There is no way of telling who is still connected.
3. Have a Client die.
4. Have that Client disconnect.
5. There is no way of telling that they have disconnected.

**ADDITIONAL INFO:**
This issue goes hand in hand with #115, as currently there is no message on when players disconnect for the remaining Clients.

**Comment by crkellen** [comment]
Oddly enough, on barony-next, when the 3rd Client is connected, and they save and exit (without saving), it tells the 2nd Client that they have left. The host receives no message. The host does not receive a message when the 2nd Client disconnects either. Updating title to reflect this.

**Comment by crkellen** [comment]
Thanks to #178, the issue about not seeing messages when Players disconnect has been fixed. However, the idea that there is no way to tell who has connected is still an issue, and as such, this still has yet to be fully implemented.

**Comment by addictgamer** [comment]
Maybe a list or sidebar could appear somewhere when !shootmode/in inventory/status/charsheet mode.

**Comment by crkellen** [comment]
My thoughts exactly. That or a Tab menu.
null

**Comment by addictgamer** [comment]
Tab could work, but I'd prefer solutions that don't add new keybindings due to limited buttons on game controllers.

**Comment by crkellen** [comment]
This was implemented though https://github.com/TurningWheel/Barony/pull/260/commits/c958817d2f265bb3f12dfaf18544fe55f602c1d5 (The sidebar added to the skills page)
