### ISSUE TITLE
[2.0.5] Spell of Opening just opens the door, doesnt unlock

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#125]
**ISSUE:**
When using the Spell of Opening on a locked door, it only opens the door, it doesn't unlock it. Causing the door to be stuck in a open state. Doors in the open state cannot be attacked, or have spells casted on them.

**EXPECTED RESULT:**
When casting the Spell of Opening on a locked door, the door should unlock, not open.

**ADDITIONAL INFO:**

**Comment by addictgamer** [comment]
Resolved in #208
