### ISSUE TITLE
[2.0.5][Multiplayer][Client] Being hit with Slow doesn't work on Client

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#126]
**ISSUE:**
If a Client is hit with the spell of Slow, it does not slow them.

**EXPECTED RESULT:**
If a Client is hit with the spell of Slow, it should slow them.

**ADDITIONAL INFO:**
This assumes that Friendly Fire is turned ON.

**Comment by addictgamer** [comment]
Resolved in #209
