### ISSUE TITLE
[2.0.5][Multiplayer][Client] Being hit with Confuse does't work on Client

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#127]
**ISSUE:**
If a Client is hit with the spell of Confuse, it does not confuse them.

**EXPECTED RESULT:**
If a Client is hit with the spell of Confuse, it should confuse them.

**ADDITIONAL INFO:**
This assumes that Friendly Fire is turned ON.

**Comment by addictgamer** [comment]
Resolved in #210
