### ISSUE TITLE
[2.0.5][Multiplayer] Being hit with Locking displays wrong message

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#128]
**ISSUE:**
If a Player is hit with the spell of Locking, it displays the message "You open the door!" on the one who was hit.

**EXPECTED RESULT:**
If a Player is hit with the spell of Locking, it should display "No telling what it did..."

**ADDITIONAL INFO:**
This assumes that Friendly Fire is turned ON.

**Comment by addictgamer** [comment]
Resolved in #211
