### ISSUE TITLE
[2.0.5] Player can cast spells while asleep

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#129]
**ISSUE:**
If a Player is asleep, they can still cast any spell.

**EXPECTED RESULT:**
If a Player is asleep, they should be unable to do anything.

**ADDITIONAL INFO:**
Although you can cast spells, you can't aim, so wherever you were looking last, is where it will shoot.

**Comment by addictgamer** [comment]
Resolved in #212
