### ISSUE TITLE
[2.0.5] Players are not notified when Slow effect wears off

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#130]
**ISSUE:**
If a Player is slowed, when the effect times out, the Player is not notified.

**EXPECTED RESULT:**
If a Player is slowed, when the effect times out, they Player should receive a message notifying them they are no longer slowed.

**ADDITIONAL INFO:**
This is mainly to be consistent. If a Player is standing still, they may not realize they aren't slowed anymore. In general, user feedback is important.

**Comment by addictgamer** [comment]
Resolved in #213
