### ISSUE TITLE
[2.0.5][DISCUSSION] Weapon Damage is less than it should be

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#139]
**ISSUE:**
Damage is currently calculated by first setting it to the `beatitude` of an item, then adding in the amount of damage the weapon should have (based on it's time), then at the end is this line:
`attack *= (double)(status / 5.0);` Which modifies the amount of damage it does based on the current Durability Status of the item. However, you cannot equip a broken item, so all weapons are doing less damage than they should be, as the maximum value it can calculate is 0.8.

**EXPECTED RESULT:**
Weapons should do the damage assigned to them, if they are excellent.
The solution is to simply set the `5.0` to `4.0`

**ADDITIONAL INFO:**
# This needs to be discussed and tested.
I will do some tests of my own, but this will raise the damage of all weapons, which could possibly make the lower levels much more difficult. Skeletons will do more damage, but so will the Players.

**Comment by addictgamer** [comment]
This has been addressed in the Blessed Addition beta.
