### ISSUE TITLE
Feature Request: Ultrawide monitor support (21:9)

### ISSUE THREAD

**Issue by StevenGlick** [TurningWheel/Barony#14]
Hi there! I just got the game and have been enjoying it, but I couldn't figure out a way to get my resolution running (2560x1080). Could we get some more resolution options or maybe a custom resolution setting?

**Comment by addictgamer** [comment]
Actually, you can edit default.cfg to change your resolution. Look for the /res line
E.g.:
/res 2560x1080

Or you can run that command in-game.
