### ISSUE TITLE
[2.0.5][Pathfinding] Entities often walk into spike traps

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#146]
**ISSUE:**
Entities do not realize spike traps exist. This is either intentional or not, but adversely affects gameplay. Followers are only useful in the Mines and Swamp because once you reach the Labyrinth and Ruins, the spike traps will eliminate almost all of them. Spike traps will also eliminate enemies, and potential followers, which removes the ability to gain experience and lowers overall difficulty.

**EXPECTED RESULT:**
Spike traps should conceptually be considered a "Player trap", a trap that is meant for the player, not the AI. All pathfinding AI should be able to know of the existence of spike traps, and avoid them as if they were unpathable blocks such as water. Perhaps if they are "retreating" (backing up when at low HP), they will still run into them (Entities can still walk on the tiles, but actively choose not to).

**ADDITIONAL INFO:**
I will have to delve into the code for this one and make sure I get it right. While I am looking into this one, I will also attempt to solve #31, #72, #73, #74, and #75.

**Comment by WALLOFJUSTICE** [comment]
Addressed in 03873d79, humans and followers don't run into spike traps.
