### ISSUE TITLE
[barony-next][Crash] Opening a chest can sometimes cause a crash

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#147]
## This is due to SPELLBOOK_BLANK_2 having a 'variations' value of 0, which causes a divide by zero crash.

**ISSUE:**
Sometimes, opening a chest will cause a crash. Windows will display the program has stopped responding message, the log does not state the cause.

This is the last line before an empty line in 'log.txt'
`[23-40-27] The chest swings open!`

Earlier, after heading down the first ladder:
```
[23-39-42] LoadMap mine32
[23-39-42] successfully generated a dungeon with 12 rooms, 5 monsters.
[23-39-42] warning: category passed to itemCurve has no items!
[23-39-42] Welcome to dungeon level 1.
```

**EXPECTED RESULT:**
The game should not crash.

**ADDITIONAL INFO:**
It's very possible this is because I do not have the official assets and I am missing some sort of dummy asset.

**Comment by lheckemann** [comment]
Can confirm. The same sort of crash happens when `/maxout2` is invoked.

**Comment by addictgamer** [comment]
Related to #57?

**Comment by lheckemann** [comment]
I'm not sure. The crash in the `/maxout2` command is caused by an item that's not included in the dummy data (black cloak) missing, and (I'm not sure if I'm remembering this part right though) the chest crashes were similarly caused by missing data.

**Comment by crkellen** [comment]
I know from using the Debugger' that the crash is caused by SPELLBOOK_BLANK not having any appearance variations. This causes a division by zero.
null

**Comment by addictgamer** [comment]
> I'm not sure. The crash in the /maxout2 command is caused by an item that's not included in the dummy data (black cloak) missing, and (I'm not sure if I'm remembering this part right though) the chest crashes were similarly caused by missing data.

I'll have to update the dummy data sometime.

**Comment by addictgamer** [comment]
> I know from using the Debugger' that the crash is caused by SPELLBOOK_BLANK not having any appearance variations. This causes a division by zero.

Will have to look into this eventually.

**Comment by crkellen** [comment]
This is likely not an issue anymore, however I have yet to extensively test to see if I can get it to happen again.

**Comment by lheckemann** [comment]
I think it *should* be solved for all the cases that occur regularly with the beta version data. But FWIW I still consider crashing on missing data to be a bug.

**Comment by crkellen** [comment]
I agree, especially since I was not able to find the exact reason why. The blank spell books had zero appearance types, but I'm not sure how exactly, as the items.txt file seemed to be fine.
null

**Comment by WALLOFJUSTICE** [comment]
The items.txt was updated to give appearance variations for blank/unused spellbooks, and random category chests now will not spawn any unused/blacklisted item assets. This shouldn't happen any longer (I think that rare multiplayer chest crash is still around though)
