### ISSUE TITLE
[2.0.5][Collision] Life Saving Amulet does not protect against boulders

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#149]
**ISSUE:**
If a Player is wearing a Life Saving Amulet and dies to a boulder trap, they will be revived, only to be damaged again, often resulting in two deaths in quick succession, rendering the Life Saving Amulet useless against boulder traps.

**EXPECTED RESULT:**
When hit by a boulder while wearing a Life Saving Amulet, if they would die, they will be revived, and wont take further damage.

**ADDITIONAL INFO:**
This is a pretty easy fix. Add a check to the boulder collision with Players, if they are wearing a Life Saving Amulet, then destroy the boulder.

**Comment by WALLOFJUSTICE** [comment]
Addressed in 41d55c71, finally
