### ISSUE TITLE
[2.0.5][Feature][Feedback] When a Player is revived by a Life Saving Amulet, there should be an effect

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#150]
**ISSUE:**
When a Player is revived after death by a Life Saving Amulet, it displays a message in the chat. This message can be easily missed, especially if there is a lot going on at the time. Missing this piece of information can cause the Player to not realize that their Life Saving Amulet is now broken.

**EXPECTED RESULT:**
After being revived, the player should both receive a message that they were revived, and an effect should happen around them, and in their vision. This helps give the player visual feedback that they were revived. It should be a unique animation, even if it is just a slightly modified Healing spell effect.

**ADDITIONAL INFO:**
This will help eliminate all of those times where you find out you actually died a long time ago, and haven't been wearing an Amulet this entire time.

**Comment by WALLOFJUSTICE** [comment]
There's a sound effect and white particle effect now 721b4077
