### ISSUE TITLE
[2.0.5] Pools of Blood can hide Items on the ground

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#151]
**ISSUE:**
When an Entity dies or spawns a Pool of Blood, small Items such as gloves, pickaxes, quarterstaffs, etc, can become hidden inside of the Pool of Blood, often obscuring it's existence from the Player.

**EXPECTED RESULT:**
Pools of Blood should be unable to fully hide Items from sight.

**ADDITIONAL INFO:**
This is referenced in #44.

**Comment by addictgamer** [comment]
Resolved in #214
