### ISSUE TITLE
Followers can attack just-joined follower

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#158]
So, if your followers start fighting somebody and then you convert them, some of your followers may remember their grudge and continue attacking your new follower, leading to infighting and perishing meatshields.

Should go through your followers list (Stat::FOLLOWERS) on new convert and tell them all to bugger off if their Entity::monsterTarget == the new follower.

**Comment by WALLOFJUSTICE** [comment]
Monsters stop punching new allies in dc81510b, merged in #384
