### ISSUE TITLE
[2.0.5][Multiplayer][Client] Clients do not have accurate positions of boulders

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#163]
**ISSUE:**
Clients will see any boulder that is not perfectly aligned (on the grid system set for it) jittering in place rapidly and not in the correct position. Moving these boulders can often make the issue worse, causing them to be very out of sync.

**EXPECTED RESULT:**
Clients should see boulders are the host does, not jittering in place and causing issues.

**ADDITIONAL INFO:**
Reasons for this existing are related to #159.

**Comment by addictgamer** [comment]
Resolved in #216
