### ISSUE TITLE
Editor: Save Name Bug

### ISSUE THREAD

**Issue by gustaf-kingq** [TurningWheel/Barony#175]
# In the editor:

Even though there isn't a window demanding anything written, if you type anything that's not a directional arrowkey or a letter in conjunction with CTRL, what you have typed will be added to the map's save name. 

The same goes with (CTRL+V) if you have a piece of text copied instead of a chunk of copied tiles directly from the stage, using the selector tool. This doesn't seem that much of an issue at first. The real problem shows up once you try to open the File tab and choose save/CTRL+S. You will no longer save your map progress to the original map but to whatever you named it even though you weren't aware. Instead there will be a new map with an incoherent name like:

- mapname.lmpwwwwd instead of mapname.lmp
- bossdungeon.lmpfirepit.lmp instead of bossdungeon.lmp

Best case scenario, instead of updating the original map when you save, the progress is saved to an entirely new lmp file. Worst case scenario if you have unwittingly CTRL+V:ed whilst having the name of another map copied and then tried to save. This will cause the map whose named you copied, let's call it map A, to be replaced with the progress of the other map you were ACTUALLY working on, let's call it map B. Resulting in:

### Required --

- An updated version of map B,
- A vanilla version of map A and
- NO unupdated version of map B.

### What you would actually have --

- An unupdated version of map B
- An updated version of map B and
- NO vanilla version of map A.

### Tips to avoid the bug if it isn't resolved:
- Be more aware. Try to remember the shortcuts in the editor that you'll use frequently like CTRL+F and most importantly; CTRL+S and CTRL+V.
- Sure there could be letters that are safe and used for shortcuts on their own without the addition of CTRL, but for safety purposes, I would consider each letter a wrench in your works were they ever to be pressed when not prompted.
- If you realize that you have a text strip copied BEFORE you accidentally paste it, simply take the selector tool and mark an area. CTRL+C and then CTRL+V in the same are or somewhere where nothing would be ruined. Now you should be safe to use CTRL+V without affecting the map name. You can even try to copy and paste a new text strip but you would just paste the piece of the map you copied earlier instead. This would reset if you were to restart the editor however.
- Meaning, if you open the editor, make it a routine to use the selector tool like above first thing you do and you should be safe for your entire working session.
- If you realize that you HAVE pasted a copied text strip but NOT saved yet, go to the tab File and use Save As... then type what you want the map to be called. It's easier to do the above option instead to spare yourself the trouble.

**Comment by WALLOFJUSTICE** [comment]
Implemented... somewhere long ago!
