### ISSUE TITLE
Removing dlls from the source tree

### ISSUE THREAD

**Issue by akien-mga** [TurningWheel/Barony#18]
First of all thanks for open sourcing your game, that's a great move. I strongly believe that most games could be both open source and commercial, and benefit a lot from building a community of co-developers around their product.

Just a suggestion for good open source software practices, feel free to ignore it if it's too much trouble for your workflow. Having dlls bundled in the source tree is a relatively bad practice, as:
- git is not made to track binary files, so they clutter the git history.
- Each update to those dlls mean adding their full size in the git history, as it can't be handled via diffs. Your libraries here are relatively small, but still, on the principle it's something to avoid.
- It encourages the use of outdated libraries, as in most cases Windows developers will just build with what is included out of the box and not care if it's a 2 year old libpng with tons of security vulnerabilities.

Additionally you seem to have more libraries bundled that you probably need (I guess you're not using libpng3, libpng12, libpng14, libpng15 and libpng16 at the same time for example).

**The solution:**
- Delete those DLLs with `git rm`.
- Add `*.dll` and `*.exe` to `.gitignore` to ensure such binary files won't be committed in the future.
:)

**The drawback:**
Obviously developers tend to bundle such dlls to make it easier to build their engine on Windows, and that's great especially for an open source game which is likely bound to have a lively modding community among Windows users.

A better way to provide such convenience dlls would be to host a zip file with those dlls somewhere on your FTP, and add a simple .bat script in your source repo to download them.

Alternatively, if you really want to keep them in a git repo, you could have a Barony-dlls git repository where you put them, and instance it in the main repo as a git submodule. (This way the default source distribution has no dlls, but they are still easy to get). I'd suggest the FTP variant over using a submodule though.

**Comment by SheridanR** [comment]
Storing the DLLs even on an FTP is probably overkill, since the game ships with all of the "official" DLLs already. That being said, the DLLs in the repo here are not only questionable, but superfluous. I wouldn't mind in the least if somebody removed them. :)

**Comment by addictgamer** [comment]
Removed DLLs in 3b019df6291778e85c85cf4385914e3311faf5bc :)
