### ISSUE TITLE
[2.0.5][Multiplayer][Client] Client does not have accurate position of Devil

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#182]
**ISSUE:**
When fighting the Devil on the 'hellboss' level, the Client will see the Devil surface from a pool of lava, then violently interpolate to a different location.

**EXPECTED RESULT:**
The position of the Devil should be accurate, and should not attempt to interpolate to a invalid position.

**STEPS TO REPRODUCE:**
1. Edit levels.txt to start at 'hellboss'
2. Start a multiplayer game
3. Watch on the Client as the Devil will violently attempt to interpolate to (the player starting position?) another position when surfacing in a lava pool.

**ADDITIONAL INFO:**
This is the same as #163. The cause is the velocity of the entity not being reset to 0.

**Comment by addictgamer** [comment]
Resolved in #217
