### ISSUE TITLE
Open source alternative to FMOD

### ISSUE THREAD

**Issue by akien-mga** [TurningWheel/Barony#20]
Partly related to #19, but would have a different resolution so opening a new issue.

To make Barony fully libre, it would be nice to have it support an open source alternative to FMOD. If you use specific FMOD features that you don't want to part with (and additionally, if you don't want to spent too much time porting the sound engine for a game you already have in production), it could be kept alongside the alternative, and the sound engine could be selected at build time via a CMake option.

Possible alternatives would be [cAudio](https://github.com/R4stl1n/cAudio) (I discovered it recently and heard many good things about it), RtAudio, OpenAL directly, SDL_mixer, SFML Audio, PortAudio, BASS... I don't have experience with most of them, but with a bit of research I'm 100% sure that you can find a great open source library that could be used as a replacement for the proprietary FMOD.

Until an alternative is implemented, it would be nice to have the possibility to disable FMOD via a CMake argument (one would thus likely lose sound support, but at least it would be possible to build without proprietary library).

**Comment by addictgamer** [comment]
Moving away from FMOD is something we've discussed -- in fact, I believe we're using OpenAL or thereabouts for future projects.

As for Barony, I don't plan on porting any of the sound code at this point, but I would be more than happy if somebody took it up to port the sound code.

**Comment by SheridanR** [comment]
We are indeed using OpenAL Soft (ie the free implementation of OpenAL) for our next project, partly because FMOD seems to be under a somewhat restricted license. At this stage it would be costly for me to  dive back into Barony and rewrite the sound engine, but if anyone else is interested that is definitely the library I would recommend for that purpose.

**Comment by akien-mga** [comment]
Thanks for the feedback. As a first step I'll probably make a pull requests to add an optional argument that disables FMOD support (and thus the sound engine) until a replacement is contributed. I don't think many users will want to play the game without sound, but just for the sake of it :)

Regarding helping replace FMOD with OpenAL Soft or another libre alternative, I might have a look at the work it implies, though I'm probably not the best fit for the job (never implemented a sound library myself).

**Comment by akien-mga** [comment]
Looks like you not only need to register an account to download FMOD Ex, but you also need to then contact support to get your account enabled for downloading it... Don't think they'll want to enable my `jdoe_onetime` junk account, so let's start with implementing a way to disable it :D

**Comment by addictgamer** [comment]
Huh, that's new. It used to be you just needed an account to download (even farther back, anybody could just come and download anything they wanted off of the website). Now you need to get your account "enabled"?

**Comment by akien-mga** [comment]
Yep: http://www.fmod.org/download-previous-products/#FMODExAPIDownloads

> **Note:** If you can’t see FMOD Ex, to get access for it for older titles, please contact FMOD Support `mailto:support@fmod.com?subject=FMOD%20Ex%20Access` (with your fmod.com username) and it will be enabled on your account

**Comment by pwhelan** [comment]
I just submitted a PR which should at least help as a starting point.

**Comment by lakp** [comment]
I've run into the FMOD stumbling block as well. Sent a request to their support email.

**Comment by addictgamer** [comment]
Pull request #22 has been accepted, you can now compile without FMOD by running cmake with `cmake -DFMOD_ENABLED=OFF`

If anybody wants to take this further and write an abstraction layer between the game and the sound implementation, I'm open to that as long as the sound implementation supports our platforms (Linux, Windows, OSX) and has the features we require (namely 3D sound).

**Comment by FreeLikeGNU** [comment]
I could not get the steam binary to work, but was able to compile using source and run the game! Thank you! Please port to OpenAL or a suitable libre substitute :+1:

**Comment by addictgamer** [comment]
OpenAL has been implemented in pull request #50.
