### ISSUE TITLE
Tag stable releases

### ISSUE THREAD

**Issue by akien-mga** [TurningWheel/Barony#21]
I've seen on Steam that the currently deployed version would be 2.0.3 beta. It would be great to have git tags for the past and current stable releases, to see the evolution of the game.

To make and push tags, it's quite easy:
```
git checkout <commit_hash_you_want_to_tag>
git tag v2.0.2
// repeat for all tags
git push --tags
```

**Comment by addictgamer** [comment]
Actually, the latest release on Steam is from before the source code was released on Github, so there's nothing to tag just yet.

However, thanks for bringing this up. I will tag future releases as they come :)

**Comment by akien-mga** [comment]
Safe to close this issue then :)
