### ISSUE TITLE
HUD scaling to fit high resolutions (HD, FullHD, 2k, 4k, etc)

### ISSUE THREAD

**Issue by akien-mga** [TurningWheel/Barony#24]
It was originally mentioned in the comments of [this Steam announcement](http://steamcommunity.com/games/371970/announcements/detail/799768937971933949), but I think it would be nice to start putting up GitHub issues with such stuff, so that potential contributors know what are the issues that they could handle.

This one is pretty straightforward: at higher resolutions, the HUD is quite small and it's thus uncomfortable. My native monitor resolution is 1920x1080, and it's too small so I'm playing in 1600x900 (and might consider going further down for a better experience).

HUD scaling should be _relatively_ easy to implement (haven't checked the source for it yet though). It could be exposed as a slider in the options (interpolated), or with a discrete parameter (fixed ratios that ensure that pixel correctness is preserved to some extent).

**Comment by addictgamer** [comment]
GUI scaling (not limited to the HUD) is definitely on the list of things to do. Unfortunately, it's not that simple to implement -- the GUI code is probably some of the ugliest and most disorderly code in the codebase.

Organizing & breaking down this project (throwing up issues) is a good idea. I'll start looking into it.

**Comment by addictgamer** [comment]
Is anybody familiar with the new "projects" feature of Github? I'm considering how to best organize this endeavor and which of Github's facilities I can and should utilize.

**Comment by Nubbie** [comment]
[Added in v3.1.7](https://steamcommunity.com/games/371970/announcements/detail/1703932624202350160) - "Added UI scaling options to the Video settings tab. Character sheet, HP/MP bars, hotbar, inventory, skills sidebar, and chat log can now be scaled via the settings menu."
This issue can be closed

@addictgamer It's a neat way to categorize and publicly display the workflow of bigger projects the game might have, like refractoring the game code or implement a DLC :) 
You can look at how some other projects are using it like in [Github/OpenRCT2](https://github.com/OpenRCT2/OpenRCT2/projects) _(know Im ~2 years late)_
