### ISSUE TITLE
[2.0.7] Fireball can set friendlies on fire with "Friendly Fire" off

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#249]
**ISSUE:**
When the "Friendly Fire" flag is set to Off, meaning Players cannot harm their allies, hitting a friendly with a Fireball spell or staff will still set the friendly on fire, causing them to take damage.

**EXPECTED RESULT:**
If "Friendly Fire" is Off, there should be no method of harming a friendly through first-party means. All other spells effects do nothing if the friendly is hit, Fireball should be the same.

**STEPS TO REPRODUCE:**
1. Start a multiplayer game
2. Turn Off "Friendly Fire"
3. Cast fireball or shoot a staff of fireball at another Player, they will be set on fire, and will take damage.

**ADDITIONAL INFO:**
I recommend this for a hotfix, if at all possible. Perhaps with a rework on Fire to make it non-random, but have some sort of maximum. See #121.

**Comment by addictgamer** [comment]
Fixed in #252
