### ISSUE TITLE
Add a "Continue"/"Resume" menu option

### ISSUE THREAD

**Issue by akien-mga** [TurningWheel/Barony#25]
In the current 2.0.3-beta (last steam build), when you start the game and want to continue with your current character, you have to click "New game", which is confusing. It then shows a popup to propose you to continue the last saved game or discard it, which against gives a bit a bad UX IMO.

There should be two different entries:
- Continue (maybe with name and class of the character next to it, e.g. `Continue  [warrior, John Doe]`)
- New game (and this one could still show a popup to warn you that you'd overwrite the current saved game)

**Comment by addictgamer** [comment]
Actually, what I've wanted to do was rename the "New Game" option to something more generic: E.g. "Start Game"
Something like that would take care of the confusion without necessitating any code changes.
