### ISSUE TITLE
[2.0.7] Hitting a friendly NPC with a spell with F.F. off aggro's them

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#251]
**ISSUE:**
If you hit a friendly NPC, such as a Human or Shopkeeper, with a spell of ANY kind, even if it reflects off, it will deal zero damage if you have Friendly Fire off, but will still aggro them.

**EXPECTED RESULT:**
Hitting a friendly with a spell should not deal damage to them, damage to their equipment, cause a status effect, or aggro them if Friendly Fire is OFF.

**ADDITIONAL INFO:**
Included in the fix for this one will be a fix for #249.

**Comment by addictgamer** [comment]
Resolved in #242
