### ISSUE TITLE
Crystal Golem should possibly deal more damage when charged

### ISSUE THREAD

**Issue by SheridanR** [TurningWheel/Barony#261]
When the crystal golem raises its arms for a charged attack, I feel it should do more damage than it currently does. My guess is that the charge applies a 2x modifier to the damage... perhaps this should be upgraded to 3x or even 4x (too crazy?)

The attack is telegraphed long enough in advance that I believe the player should be able to escape the blow by moving away from the golem. Having to dance among golems and other critters could possibly add a lot to the fun factor and challenge.

**Comment by WALLOFJUSTICE** [comment]
Been addressed in the beta, multiplier is now 4x from 2x (was using the max charge damage), don't get hit!
