### ISSUE TITLE
Tiles should have entity buckets

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#278]
Every tile should keep track of the entities that are on them. This is a huge boost for efficiency, since right now whenever you search for an entity, you have to look through the entire map's entities list. If tiles had a list of pointers to the entities on them, then finding entities would be much much faster in multiple cases.

**Comment by addictgamer** [comment]
Short-term low-cost solution for performance issues might be to just have a global monster list.

**Comment by WALLOFJUSTICE** [comment]
Sorted ages ago, not sure why didn't close this.
