### ISSUE TITLE
Any skills that are maxed out should not give you further experience (e.g. free magic missile casting)

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#279]
Right now, after you unlock the spellcasting capstone, you can spam magic missile and get infinite XP from "levelling" your spellcasting skill.
That should not happen, you've already maxed out the skill!
Same applies to all other skills.

**Comment by crkellen** [comment]
I believe this was fixed in the latest patch.

**Comment by addictgamer** [comment]
Correct.
