### ISSUE TITLE
[3.0.0-beta] Beartraps can be placed on air

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#287]
**ISSUE:**
Beartraps can be placed anywhere, including floating on air, if you are levitating.

**Comment by Nubbie** [comment]
@crkellen [Fixed in **V3.1.7**](https://steamcommunity.com/games/371970/announcements/detail/1703932624202350160) - "Fixed issue where bear traps could be placed in air gaps while levitating."
