### ISSUE TITLE
Casting sleep on minotaur, Herx, and shopkeepers displays wrong messages

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#298]
Says "The minotaur falls fast asleep!"
Should probably say "This spell has no effect on the minotaur!"

**Comment by addictgamer** [comment]
Same with Herx

**Comment by WALLOFJUSTICE** [comment]
The spell does put them to sleep, then later in code wakes em up. Should probably add the exception before they are slept

**Comment by addictgamer** [comment]
Shopkeepers also affected.

**Comment by lheckemann** [comment]
There are a couple of monsters in the crystal caves that also don't sleep iirc.

**Comment by WALLOFJUSTICE** [comment]
Sleep spell uses Entity::setEffect now to check whether or not to actually sleep the monster. Fixed in earlier patch this year.
