### ISSUE TITLE
Some items cannot be stacked unless dropped from inventory first and then picked up

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#299]
What it says on the tin.

Should be able to drop items onto eachother to stack them if picking them up would have stacked them.

**Comment by WALLOFJUSTICE** [comment]
Rocks? These are identified instantly so won't stack by the time you click on the next unidentified one. So exception should be made there

**Comment by addictgamer** [comment]
No, meat and potions of sickness in this case. I had to drop all my meat and pick it up again, and the same with me 3 swirly green +0 potions of sickness (not my cloudy green potion of sickness, that one didn't stack either way).

**Comment by lheckemann** [comment]
I think it's perfectly correct that unidentified items don't stack with identified ones. Maybe they should stack once identified though. In any case, I'm pretty sure it's the identification status that stops them from stacking.

**Comment by addictgamer** [comment]
> In any case, I'm pretty sure it's the identification status that stops them from stacking.

No, the issue is that the items were identified and completely identical. There's no way to stack them unless you drop them out of your inventory and pick them up again. Trying to drop them on top of eachother in the inventory GUI just makes you swap your held item with the one on the grid. What should happen is you stack them.

**Comment by crkellen** [comment]
In addition to the drag and drop feature, it would be good to make it simply check for stack on appraisal, check for stack on pickup, and if a reorganize inventory feature is added, check for stack there as well.
null

**Comment by addictgamer** [comment]
f21c2f96caab64644623bfb0d034b992a71acfa3 now makes them auto-stack after they're appraised.
