### ISSUE TITLE
Entity UID searching in netcode is inefficient

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#302]
What it says on the tin.

There are multiple packets the client receives on a regular basis with entity UIDs inside. What does the client do? It searches the entire entity list.
This is bad. Notice I left a key phrase out: "until they find the UID." That's because there is no until, they keep on searching even after they've found the entity UID (perhaps there's a technical reason for this? Will have to investigate further). Right off the bat, that's ripe for improvement.

Ultimately, though, it'd be much better to create a system where, given an entity UID, you do not need to perform any searches (not only for netcode, but any and all entity UID lookups in general). Instead, you can access the entity directly (didn't we implement entity hash tables or somesuch a while back? Will need to look into this more, here's the poster-child of use cases).

This is definitely one possible improvement to multiplayer client performance.

**Comment by lheckemann** [comment]
cd50ff8

**Comment by addictgamer** [comment]
Huh.

A pull request would be appreciated :)

**Comment by WALLOFJUSTICE** [comment]
Reimplemented @lheckemann's commit in 65fa6f35, will be added in #386. Missed this one, looks like it'll be a big improvement!!
