### ISSUE TITLE
Artifacts are too common

### ISSUE THREAD

**Issue by lheckemann** [TurningWheel/Barony#307]
On a recent run, I obtained:

- 7× Dyrnwyn
- 3× Sharur
- 3× Gungnir
- 1× Khryselekatos

I think they should maybe be a *little* rarer.

EDIT: Also multiple artifact helms/breastplates/cloaks/etc

**Comment by crkellen** [comment]
That's amazing.I haven't found a single one except the always persistent Gungnir in the Minotaur maze.
null

**Comment by lheckemann** [comment]
It might just be my habit of exploring all the levels 100%

**Comment by crkellen** [comment]
I do as well, unless prevented by chasms or walls with no way through. My friend who also uses Windows has had a game with three Shelobs. I've never seen anything other than Algernon on barony-next or 3.0.
null

**Comment by lheckemann** [comment]
I did a playthrough yesterday on the steam version where I didn't get a single artifact either. I'm confused!

**Comment by crkellen** [comment]
That's "random" for you, haha. It could definitely be looked at. A simple "has this item/monster that drops item, been spawned? If so, don't spawn it anymore (other than gungnir in maze)"
null

**Comment by lheckemann** [comment]
That would bias their appearances to earlier in the game.

**Comment by lheckemann** [comment]
I've found Dyrnwyn and Sharur just lying around or in chests, not just on Shelob/Potato King. King Arthur also carries Dyrnwyn, and can be found at any stage of the game (most likely Minetown or Mystic Library just because they have lots of humans).

**Comment by WALLOFJUSTICE** [comment]
Which version? 3.0 should just be from humans/monsters, no chests.

And each monster is a 1 in 50 to spawn a boss, humans are 1 in 25 to be special, then 3 of 10 carry artifacts

**Comment by lheckemann** [comment]
I've been running barony-next and found artifacts just lying around on the ground like regular items.

**Comment by WALLOFJUSTICE** [comment]
Hmm.. do you have a items/items_global.txt file in that directory? If that's not there you'll likely have every possible item available to spawn on the ground. Copy that from the steam directory.

**Comment by lheckemann** [comment]
Yes, I have it, and it also looks to me like it should fail when the file isn't found:

https://github.com/TurningWheel/Barony/blob/ded646eec0f74f7b9306e0ecc88ce4304aaba81b/src/init.cpp#L2444-L2452

**Comment by WALLOFJUSTICE** [comment]
Just had a check and the items.levels aren't initialised elsewhere, and if the file wasn't found it'll move on since the return value hasn't been used.. could find some strange things.

Good spot on that getLinesFromFile

**Comment by lheckemann** [comment]
Closed in #318
