### ISSUE TITLE
No version check in networking

### ISSUE THREAD

**Issue by lheckemann** [TurningWheel/Barony#309]
I tried to play a game with a friend, not realising that he didn't have the beta version. The result was a "connecting, please wait" screen that never completed. Clients and servers should detect version discrepancies and fail to connect noisily.

**Comment by crkellen** [comment]
I actually wrote this down in my notebook back when I first started working on Barony. I never got around to making the PR.
+1 to this.
null

**Comment by SheridanR** [comment]
They do version check. Not sure why it didn't work in this case.

**Comment by crkellen** [comment]
One of the main issues I know of is that there is no check to see if the host's map is the same as the clients. It will just simply crash all of the clients.

**Comment by WALLOFJUSTICE** [comment]
Addressed in V3.3.5
