### ISSUE TITLE
NPC/Player Companion Walking Into Chair

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#31]
Bloke's stuck perpetually walking into a chair.
![screenshot 2016-10-21 01-33-48](https://cloud.githubusercontent.com/assets/346089/19591964/868d1d8a-972e-11e6-8b73-e22caadade45.png)
It's not even funny.

**Comment by addictgamer** [comment]
![screenshot 2017-05-26 03-07-37](https://cloud.githubusercontent.com/assets/346089/26493637/8156fa56-41cf-11e7-9808-92afd34b6b3c.png)
Possibly related? One of my followers was pacing back and forth in that hall, maybe because there was a chair and a table in it.

**Comment by WALLOFJUSTICE** [comment]
Enemies attack furniture if they happen to walk into it now, so wont get stuck endlessly at least.
