### ISSUE TITLE
Keep inventory on death

### ISSUE THREAD

**Issue by deevz** [TurningWheel/Barony#324]
In multiplayer, dying currently entails having your loot spread on the ground. Sorting through all this loot is a tremendous amount of micromanagement for the remaining allies. It would be great to have a mode that lets people re-spawn with their full inventory upon resurrection, while maintaining a durability penalty to keep it balanced.

**Comment by lheckemann** [comment]
Personally I'd prefer some new inventory UI that automatically sorts items into categories as a solution to this problem. A durability penalty, while being appropriate for balance purposes, wouldn't be much fun IMHO. That's obviously a complex solution that would require significant design and implementation effort though.

**Comment by WALLOFJUSTICE** [comment]
We've introduced auto sorting as a hotkey/inventory button so should be a lot easier to recover from death!

**Comment by deevz** [comment]
@Ihechemann, the durability loss is already part of death, from my understanding. I often find myself losing many pieces of gear after death in multiplayer. My suggestion is this merely to remove gear drop on death; let it respawn with the player.

**Comment by lheckemann** [comment]
Are you sure this is something that's happening on death as opposed to just being regular wear on items that you've been using? I don't think I've ever seen that happening.

**Comment by Nubbie** [comment]
This maybe could be a map flag like Minotaur and hunger
Or atleast 50% of the items to balance it

**Comment by WALLOFJUSTICE** [comment]
Added in January, thanks for the suggestion. Took a while to circle back to this idea 👍
