### ISSUE TITLE
Auto-Appraise Rock Failure Spam

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#35]
Auto-appraise a rock. If your perception and appraisal are too low (*warrior*), it spams your log with "failed to appraise" messages.

**Comment by lakp** [comment]
Picking up a rock leads to an infinite appraisal loop but cheese managed to level up appraisal to novice resulting in a successful appraisal after a while. Seems like the options to fix this are:

1) Add a check for rock, -1 perception and appraisal: none during auto-appraise.
2) Let rocks have a chance of improving appraisal. However this results in appraisal leveling up almost instantly.
3) Rock appraisal can't fail, unless it's the luckstone.

Thoughts?

**Comment by addictgamer** [comment]
I was going to make rocks about as tough to appraise as cheese is (which would also make it improve appraisal).

**Comment by addictgamer** [comment]
I'm going to go with option 3. That's a good idea.

**Comment by lakp** [comment]
Just noticed the setting->gameflags clicking areas are offset by one space upwards.

**Comment by addictgamer** [comment]
That should have been fixed in 10c6673cd5237b5620bc18f9fb90a9c52771d7b3
Are you still encountering the issue after that commit?

**Comment by lakp** [comment]
Yeah sorry. Forgot to sync to this repo.
