### ISSUE TITLE
[Game crash] Repetitively spamming a key while loading models, crashes game

### ISSUE THREAD

**Issue by Nubbie** [TurningWheel/Barony#362]
**OS:** Windows 10
**Version:** 3.1.4

If you repetitively spam a key as the game is loading its models in fullscreen, it crashes

**Steps to reproduce:**
1. Start the game in fullscreen
2. Repeatably try to open the Steam overlay while models load

**Edit**: Seems to happen too if you interrupt the "loading model" procedure by tabbing out of the game
**Edit 2:** Seem to be happening when you spam ANY key

**Comment by addictgamer** [comment]
How does it crash? Does it say "Barony has stopped responding"?

**Comment by Nubbie** [comment]
Can not reproduce this in 3.1.7
