### ISSUE TITLE
Use a portable PRNG like MT instead of rand()

### ISSUE THREAD

**Issue by ToxicFrog** [TurningWheel/Barony#38]
Currently, Barony uses rand() for random number generation. This is fine on Linux (where rand() uses the same algorithm as POSIX random()), but Windows rand() is infamously bad, with very little randomness in the low bits (i.e. the ones you're using most of the time) and obvious patterning.

Switching to random() is a no-go, since Windows doesn't have it available, but it should be possible to replace it with a known good PRNG like Mersenne Twister and use that for all RNG regardless of platform. This has the added advantage that the same seed will produce the same results even on different OSes.

**Comment by addictgamer** [comment]
Actually, Barony does not exclusively use rand(). It uses prng_get_uint() in places where synchronization across platforms matter.

Everywhere else, looks like it still uses rand(), but find+replacing it would change that.

**Comment by SheridanR** [comment]
rand() is used wherever the quality of the results really do not affect on gameplay. For everything else, we already use our own RNG. For consistency, perhaps we should've used our own RNG for everything, but we didn't identify that we needed one until rand() was already everywhere in the codebase.

Also, our RNG is already used to synchronize results across platforms. When a party of players descends a level, the server just generates a 32-bit seed and sends it to the clients. Everybody then generates the whole level and everything in it themselves.

**Comment by ToxicFrog** [comment]
Aah, I didn't notice prng_get_uint() -- I was looking at level-up and skill-up code, which is all rand().

Speaking of level-ups, how open are you to gameplay-changing patches? I've been kicking around the idea of a more Nethack-like way of selecting stats to level up, by weighting them based on how much the player has been exercising their corresponding skills since the last level, rather than the current behaviour (which, if I'm reading this right, picks three stats at random to increase, with a slight bias away from STR and CHR and a possibility of duplicates, but not triplicates). But if you're happy with the way it currently works, I don't think I want this quite enough to maintain my own patchset on top of the official repo.

**Comment by addictgamer** [comment]
> I've been kicking around the idea of a more Nethack-like way of selecting stats to level up, by weighting them based on how much the player has been exercising their corresponding skills since the last level

Actually, we originally planned to do something similar to that.
That said,

> Speaking of level-ups, how open are you to gameplay-changing patches?

It depends. In this specific case, after talking with the team, I think it should go into a side branch (or somesuch) first so that it may be tested before we consider merging it into master. We're not married to the way stats level presently, but we do want to see what consequences this change would have on gameplay.

**Comment by addictgamer** [comment]
Going to close this, since all synchronization-critical code should already be using PRNG.

If somebody wants to go ahead and replace rand() with PRNG that's fine by me, but not necessary.
