### ISSUE TITLE
[Enchantment] Puking when drinking too much booze

### ISSUE THREAD

**Issue by Nubbie** [TurningWheel/Barony#389]
In update 3.2.0, nothing happens if you drink too much booze

You maybe should have a limit where it warns the player and then puke - as it does with food

**Comment by lheckemann** [comment]
https://github.com/TurningWheel/Barony/blob/667a4ed961c288d25aecfb796357ecc8c32c394e/src/entity.cpp#L2498-L2513 you aren't guaranteed to vomit from drinking booze — it's a random effect.
