### ISSUE TITLE
Use a high-resolution timer and ditch sleep/usleep.

### ISSUE THREAD

**Issue by exezin** [TurningWheel/Barony#397]
It appears the interal framerate limit/timestep has some glaring issues.

The first of which being the use of SDL_GetTicks, which is inaccurate and very inconsistent, this should be replaced with getPerformanceCounter and getPerformanceFrequency.  See [here](https://gist.github.com/shakesoda/11238165) for an example of this method.  This can often be a pretty big issue as obviously, logic relies on delta times and such, and GetTicks just isn't as accurate as you want that to be.

The second issue is down to the use of sleep, which only guarantees a minimum time to sleep for, and in some instances sleeps for longer than you want it to.  There should also be an option to disable the frame limit entirely and just let the game run as fast as it can.  This isn't *as* big of an issue.

I know it's said often, but [fix your timestep](https://gafferongames.com/post/fix_your_timestep/) (is a great article)

There's a third issue that's not *directly* related to this but I think should be mentioned, mouse input with vsync enabled is horrendously slow.  It's the typical vsync input latency and feels awfully sluggish.  The camera should rotate the same amount and at the same speed regardless of framerate, so there are obviously a few issues here with how you poll/queue up mouse deltas and use them or something.

**Comment by WALLOFJUSTICE** [comment]
Merged in #398
