### ISSUE TITLE
'Character Status' opens when pressing "e" on keyboard whatever I set in 'Bindings' menu

### ISSUE THREAD

**Issue by Adrien2002** [TurningWheel/Barony#406]
I built Barony with this commit : 918becf2f32732b1301ee7e6ba35d1e2e2f7f057 (24th December 2018) on my FreeBSD. Everything is working fine BUT whenever I press "e" on my keyboard, it opens the Character Status. Pressing "e" again won't close the inventory as it would normally do when pressing the Character Status key again to close the inventory.

I wanted to use "e" to "Use" (IN_USE)

> $ cat .barony/default.cfg|grep IN_USE
/bind 8 IN_USE

>$ cat .barony/default.cfg|grep bind\ 8
/bind 80 IN_TURNL
/bind 82 IN_UP
/bind 81 IN_DOWN
/bind 8 IN_USE

I don't have double bind on "IN_USE"
I tried to put the mess in my bindings by changing everything, removing "e" key but whatever I do, pressing "e" always opens the menu.

My game version is the one from GOG (3.2.2). In case it is important for the future : 
https://i.imgur.com/mSe1CJE.png
https://i.imgur.com/lXxHBCX.png

**Comment by devnexen** [comment]
Just for curiosity, did you encounter other (or same) issues with the FreeBSD port (or pkgsrc-wip ?) as they both using the real 3.2.2 release version ... before compiling by hand ?

**Comment by Adrien2002** [comment]
> Hello,
> 
> I do notice the 'e' key will open the character sheet if the right side panel is unlocked. This is a function of the 'cycle through NPCs' command. If both are bound to the same key then the open character sheet will occur before "use" and not allow the "use" interaction. Can you confirm the 'cycle through NPCs' key has been rebound as well?
> 
> ![image](https://user-images.githubusercontent.com/12412707/50770460-86c97c00-12db-11e9-9d3a-1e077519f7cf.png)

That's weird, I'm sure that I tried to change this key... I just tried and indeed it works. I must have done something wrong during my tests so my changes didn't apply cause before to open this issue, I was sure it wasn't working even changing that "Cycle Through NPCs" key.

Clicking on the lock upper right in the corner, in the character status, will also avoid the inventory to open up pressing the "Cycle Through NPCs" key. Good to know !

Thank you WALLOFJUSTICE, I'm an idiot...
