### ISSUE TITLE
Skeleton Regen Not Active

### ISSUE THREAD

**Issue by KenloMishuma** [TurningWheel/Barony#415]
On 3-9-2019 I ran into an issue where the class-based regen for skeletons was not working for my char.  This issue persisted through about 26 levels of the game.

**Comment by WALLOFJUSTICE** [comment]
Regeneration is disabled when hunger is off, this is probably what you were experiencing?

Anyway made an exception for skeletons to always regen every 48 seconds in commit 
653a20e, live on Steam now.
