### ISSUE TITLE
Cannot load multiplayer save on Linux (CTD)

### ISSUE THREAD

**Issue by Tritonio** [TurningWheel/Barony#422]
https://www.gog.com/forum/barony_cursed_edition/ctd_when_loading_mp_save

When I try to load a multiplayer save the game crashes to desktop immediatelly and this is thrown in the terminal:

Running Barony: Blessed Addition
[23-36-51] Data path is ./
[23-36-51] Output path is /home/user/.barony
Caught segfault at address 0x35533118

This only happens with multiplayer saves that had more than one player in the game.

I am on Linux Mint 19.1 MATE 64-bit.

Affects version 3.2.3 of the game, as found on GOG.

**Comment by WALLOFJUSTICE** [comment]
Hi sorry I hadn't seen your post until someone brought it to my attention last week. I've got a fix submitted to GOG which might take some time but in the meanwhile see attached for fixed binaries.

Let me know if it works.

[baronyDRMfree_v3.2.3Jun19.zip](https://github.com/TurningWheel/Barony/files/3328094/baronyDRMfree_v3.2.3Jun19.zip)

**Comment by Tritonio** [comment]
It works! Thank you!
