### ISSUE TITLE
Resolution list is overlapped by settings below it

### ISSUE THREAD

**Issue by M4R10zM0113R** [TurningWheel/Barony#424]
If having more than 24 resolutions to pick from, the rest get overlapped by the sliders and their text
![2019-08-23-072323_908x653_scrot](https://user-images.githubusercontent.com/3507989/63595764-f2184380-c576-11e9-9d10-a4495998e697.png)

**Comment by WALLOFJUSTICE** [comment]
Addressed in V3.3.5
