### ISSUE TITLE
Repairing a tinkering kit with itself may crash the game

### ISSUE THREAD

**Issue by lheckemann** [TurningWheel/Barony#431]
Title says it all, I guess?

**Comment by WALLOFJUSTICE** [comment]
Client or server? Is it reproducible - does the kit need to be decrepit or something?

**Comment by lheckemann** [comment]
This is happening in single-player mode, I have a save where I have the tinkering kit and enough scrap to repair it; loading this save and trying to repair the kit will sometimes work and sometimes crash: https://sphalerite.org/savegame0.dat

**Comment by lheckemann** [comment]
This happens both on steam and on my own build from current master (747d106).

**Comment by WALLOFJUSTICE** [comment]
Was it equipped at the time?

**Comment by WALLOFJUSTICE** [comment]
I've tried to replicate no luck, is it possible to get a stack trace or breakpoint?

**Comment by lheckemann** [comment]
The crash is at:

```
#0  0x00000000005f3d8b in GenericGUIMenu::updateGUI (this=0x8a6100 <GenericGUI>)
    at /home/steam/barony/src/interface/interface.cpp:3361
#1  0x000000000043fec1 in main (argc=<optimized out>, argv=<optimized out>) at /home/steam/barony/src/game.cpp:4049
```

I can send you a core file privately.

**Comment by lheckemann** [comment]
The problem seems to be the access to `tinkeringKitItem->node`  — the `tinkeringKitItem` pointer is probably into freed/reallocated memory, since none of its members' values make any sense.

**Comment by WALLOFJUSTICE** [comment]
Ok cool, I think I've got a lead on this, is the kit equipped or not when you repair it?

**Comment by lheckemann** [comment]
Ah yes, it seems to work when it's equipped…

**Comment by WALLOFJUSTICE** [comment]
Could you please try PR #432 and see if that fixes the issue?

**Comment by lheckemann** [comment]
Yes, that seems to fix it. Thanks!
