### ISSUE TITLE
Some items are invisible when dropped

### ISSUE THREAD

**Issue by lheckemann** [TurningWheel/Barony#434]
A number of the new items (tinkering kit, alembic, both types of scrap, quivers) aren't visible once dropped, and thus can't be picked back up. I don't think this is intentional, are the models maybe missing?

This is on the Steam version, Linux, singleplayer.

**Comment by addictgamer** [comment]
Looks fine to me?

![Screenshot 2020-01-10 12-58-10](https://user-images.githubusercontent.com/346089/72186122-595d5580-33a9-11ea-8433-de340ccfcabe.png)
Perhaps try re-validating files?
(Could you also check if the text files like models/models.txt have dos line endings or *nix?)

**Comment by lheckemann** [comment]
Sorry, my fault, outdated model cache…
