### ISSUE TITLE
Stuck connecting to server ...

### ISSUE THREAD

**Issue by ganthore** [TurningWheel/Barony#442]
The other day I tried to play Barony with one of my friends and he attempted to connect to my game and was stuck connecting to the server ...

After some debugging, I discovered that my Linux version of the game was older thank his version on windows. The version mismatch was between 3.3.2 (windows ) vs 3.3.1 (linux). At the time, Linux didn't have an update available, so it was impossible for us to play in this situation. I figured out the version mismatch was the problem only when I tried to do direct IP connect (steam didn't bother reporting the version difference).

The clear workaround was for me to play Barony in windows and that worked fine, I just wanted to note that steam component isn't accurately reporting the version mismatch when connecting over steam since it was getting stuck "connecting to server" between both clients.

**Comment by WALLOFJUSTICE** [comment]
Thankyou, will improve the popup message.

**Comment by WALLOFJUSTICE** [comment]
Upcoming V3.3.5 improves mismatch handling and shows messages prior to connecting
