### ISSUE TITLE
Extra marker in text data

### ISSUE THREAD

**Issue by sebleblanc** [TurningWheel/Barony#449]
https://github.com/TurningWheel/Barony/blob/b70f35d9b8c89e43265ddd0fe528de6867b1eece/lang/en.txt#L1233

Is this marker extraneous? It shows up inside the game.

https://vignette.wikia.nocookie.net/baronygame/images/e/eb/LoZ_ref.png/revision/latest?cb=20160215033108

**Comment by WALLOFJUSTICE** [comment]
Hi, which platform are you running Barony on?

On windows I get the correct message: 
![image](https://user-images.githubusercontent.com/12412707/77533154-77d3e700-6eea-11ea-8667-49d314485514.png)

**Comment by sebleblanc** [comment]
I was basing myself off of this page here : https://baronygame.fandom.com/wiki/Easter_Eggs

If this issue has already been fixed, then I apologize for having brought it up.

**Comment by WALLOFJUSTICE** [comment]
All good, we appreciate the time taken to raise issues!
