### ISSUE TITLE
Entity Hash Tables

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#45]
Right now, Entities use a plain old list. Adding a hashtable should have substantial performance boosts since `uidToEntity()` very frequently occurs throughout all the code.

**Comment by ptitSeb** [comment]
I have implemented that using an std::unordered_map<uint32_t, node_t*> 
And putting entitie::uid as private, accessible only with GetUID() (an inline read accessor) and SetUID() (that update the map).
Is it acceptable?

**Comment by srathbunvl** [comment]
Yes, that would definitely solve the problem quite nicely :)

**Comment by addictgamer** [comment]
Forgot to close this, was implemented in PR #54.
