### ISSUE TITLE
[Request] Increasing EXP Share range, an option?

### ISSUE THREAD

**Issue by Masti6** [TurningWheel/Barony#450]
At game.hpp line 302,
#define XPSHARERANGE 256
Is it possible to increase said variable in any config file post-compilation?
If not, would it perhaps be possible to add an option with a slider from 0 (0%) to 16 (1 tile, 1%) to 1600 (100 tiles, 100%)? I understand doing that would be going over the 8-bit value into 16-bit territory and thus using more memory but since it'd only be for this variable, the effect shouldn't be that large on the overall performance of the game.
Perhaps just read that value from a config-file where players could change it from there if they wish?

Currently, this exp share range is a make or break situation for some people, who straight-up refuse to play the game until there's a workaround. I get you might not care about those few but if it isn't too much trouble, you'd see at least a few more satisfied fans popping up via the creation of such an option.

It's not a nice feeling being left behind by even a few levels in a game where you need every bit of exp you can get for the final trials, just because you were managing your inventory or picking up that shiny ring in the corner while your friend happened to kill something just outside the 16 tile range, especially since there is no indicator of whether or not you're in the EXP range or not.

**Comment by DrWhoCares** [comment]
The snowballing of dying once early on is real. Honestly one of the biggest design issues in the game.
I can look into this later and see if I can come up with a viable solution the devs might agree with.

**Comment by WALLOFJUSTICE** [comment]
Added in V3.3.4 using gamemodifiers.json, modifying xp_share_range to 10000 or something
`{
    "version": 1,
    "xp_share_range": 10000
}`
