### ISSUE TITLE
Which commit corresponds to 3.2.3?

### ISSUE THREAD

**Issue by rapenne-s** [TurningWheel/Barony#475]
Hi,

On GOG, latest version available is Barony 3.2.3 hotfix 1 but in the github engine sources releases, there are versions 3.3.0 and 3.2.2 but no release for the version 3.2.3.

Is there a commit that would correspond to 3.2.3 hotfix 1?

**Comment by WALLOFJUSTICE** [comment]
Hi - 8e5eb94f86eb73d92e842cca7b4a6a27de2886e2 is roughly the commit from memory, I'll tag it now.

**Comment by rapenne-s** [comment]
With the version you tagged I've been able to play Barony with the assets downloaded on GOG (version 3.2.3) on OpenBSD.

We were provide a package with the 3.2.2 version so people downloading the game on GOG were not able to play anymore.

Thank you very much.
