### ISSUE TITLE
Crash in miscellaneous menu

### ISSUE THREAD

**Issue by Gilgatex** [TurningWheel/Barony#5]
When you mouse over any of the flags at the bottom of the miscellaneous menu, the game crashes.

Re-built with code from just before my changes, it still crashes.

Tested with beta 2.0.3 on steam and no crash.

**Comment by addictgamer** [comment]
Make sure your lang/en.txt has the entries for the game flags tooltips found at the end of the steam beta 2.0.3 branch's copy.

**Comment by Gilgatex** [comment]
Confirmed, bug still exists with latest 2.0.3 beta lang/en.txt.  What lang numbers should I have for the tooltips?  On the beta version, it doesn't crash, but there are also no tooltips, so I can't compare.

Which brings up a couple points:
1) lang/en.txt should be included in the source control
2) the lang array should be fully initialized with blank strings so a crash doesn't occur if someone has the wrong lang file.

**Comment by Gilgatex** [comment]
Added filler tooltips for 1942 through 1946 and game no longer crashes.  Beta does not come with these filled.

I tested using the new lang file with stock beta.  Still not crashing (or showing tooltips).  

The most likely cause of the issue is that the tooltips on the miscellaneous menu were implemented after the beta release, so I did not have the most up-to-date language file.

**Comment by addictgamer** [comment]
Oh. Completely forgot those tooltips were added after the latest release. My apologies.

**Comment by Gilgatex** [comment]
How do you feel about my two suggestions?

**Comment by addictgamer** [comment]
1) I would like that, but I need word from the big boss man before I may throw it in the repository.
2) That's a good idea.
