### ISSUE TITLE
Invisibility causes the light spell's orb to become jittery/stuck

### ISSUE THREAD

**Issue by YellowAfterlife** [TurningWheel/Barony#56]
Using teleportation items multiple times in a row (e.g. placing a blessed mirror on hotbar and holding down the according key) causes the light spell's "ball" to move at increasingly high speeds before finally starting to actively teleport through corners and periodically getting stuck at one spot (supposedly being unable to reach destination because of skipping it). The second looks like as following: https://gfycat.com/UnsightlyAnotherDodobird

Needless to say, the usefulness of the spell is impacted negatively if it's getting stuck every now and then.

Save file: [light-spell.zip](https://github.com/TurningWheel/Barony/files/923203/light-spell.zip)

Related question: Is it intended that use of mirror may result at teleporting into lava pools or onto spike traps?

**Comment by addictgamer** [comment]
Thanks for the report. The light spell does have some oddities such as what you're seeing.
I suspect this specific issue could be fixed by teleporting the light with the player.


Related answer: Yes. Teleportation intentionally does not look for such hazards.

**Comment by YellowAfterlife** [comment]
Upon further testing, it seems like the light jitter issue is actually related to being invisible - the light spell' movements get glitchy when you put on an invisibility ring/cloak, and smooth out again when you take it off.

I have not set up a local copy accordingly to compile and test, but I'm inclined to believe that this is because
* Light ball [checks](https://github.com/TurningWheel/Barony/blob/a1d4d7a288ce1fcd630871aa3120e753bd3883ee/src/magic/actmagic.cpp#L379) that lineTraceTarget returns player
* lineTraceTarget [uses findEntityInLine](https://github.com/TurningWheel/Barony/blob/a1d4d7a288ce1fcd630871aa3120e753bd3883ee/src/collision.cpp#L957) to find the first entity.
* findEntityInLine [skips](https://github.com/TurningWheel/Barony/blob/a1d4d7a288ce1fcd630871aa3120e753bd3883ee/src/collision.cpp#L633) entities that have BLOCKSIGHT flag set to false.
* Player [sets](https://github.com/TurningWheel/Barony/blob/a1d4d7a288ce1fcd630871aa3120e753bd3883ee/src/actplayer.cpp#L773) their BLOCKSIGHT flag to false while invisible.

So the light spell is thinking that there's no line of sight to the caster and constantly doing pathfinding even though it shouldn't..?

I guess that would be solved by changing
```cpp
if (hit.entity && hit.entity == parent)   //Line of sight to caster?
```
to
```cpp
if (!hit.entity || hit.entity == parent)   //Line of sight to caster?
```
Since `hit.entity` does not seem to be used for anything else in the related code, it doesn't look like there would be any side effects.

Light getting lost after teleportation would indeed probably best resolved by just teleporting the ball of light together with the player.

**Comment by addictgamer** [comment]
Ah yes, invisibility is a known issue with the light spell.

I didn't exhaustively test it out, but it seems that change fixed it. Much appreciated.

**Comment by addictgamer** [comment]
Regarding teleportation, I think the current behavior is fine. The light spell is able to travel through terrain, so it should always end up at the player.
