### ISSUE TITLE
Can I hide the debug info in the top left corner?

### ISSUE THREAD

**Issue by jacekjarosz55** [TurningWheel/Barony#561]
I've build the game on linux with CMake, and set the flags-DFMOD_ENABLED=ON -DOPENAL_ENABLED=OFF -DCMAKE_BUILD_TYPE=Release 

and the velocity debug info appears on the top left corner on the screen, blocking the appraising popup?
I couldn't find any way to disable this. 
![obraz](https://user-images.githubusercontent.com/72438686/103028262-b1a84b80-4557-11eb-8716-0a0f40328532.png)

**Comment by SheridanR** [comment]
Hi there, can you try compiling from one of the release tags instead? If you pull master you will get the bleeding edge which might have outstanding issues like this. Thanks.

**Comment by jacekjarosz55** [comment]
Thank you for your answer. Building from the 3.3.7 release tag fixed it.
