### ISSUE TITLE
Broken textures in barony 3.3.7 on Arch linux

### ISSUE THREAD

**Issue by jacekjarosz55** [TurningWheel/Barony#568]
Recently textures in my game all started appearing mismatched everywhere. I don't know what the reason might be. I got the game data from the Epic Games Store version of the game. 

I dont know what might have caused it, but I first noticed that when I ran the editor for the first time.
Maybe something related to a system upgrade?
the problem persisted when the game was copied to a different machine, also with arch linux.
 
![Screenshot_20210126_144909](https://user-images.githubusercontent.com/72438686/105853259-c7d97980-5fe5-11eb-8161-8e7f6321ac32.png)
![Screenshot_20210126_145053](https://user-images.githubusercontent.com/72438686/105853385-ed668300-5fe5-11eb-8341-b66f4eb51768.png)

**Comment by WALLOFJUSTICE** [comment]
Hi - on Arch we think there's a newer set of SDL libraries that get distributed with Steam or the like. It's not picking up the .so files from the game's directory.

When running from Steam, our fix was to add something like this to the launch options for the Barony Steam properties:
LD_PRELOAD="$LD_PRELOAD ./libSDL2-2.0.so.0 ./libSDL2_ttf-2.0.so.0 ./libSDL2_image-2.0.so.0" %command%

So try append that before running the binary from the command line?

**Comment by jacekjarosz55** [comment]
That probably would solve the issue, but  game isn't from steam. It originally was a windows epic games store version, so all of the libraries are in form of .dll files. Is there any way I could get the needed libraries?

**Comment by jacekjarosz55** [comment]
Ok I fixed the issue by getting the libraries from Ubuntu 20.04 and preloading them with the command, but i also had to preload 
libwebp.so.6 for it to work.

**Comment by WALLOFJUSTICE** [comment]
Glad you got it sorted.

I checked the package directories, Arch seems to be on SDL 2.0.14 (latest). Ubuntu 16.04 is SDL 2.0.4 / 18.04 is SDL 2.0.8 / 20.4 is SDL 2.0.10. So there's a breaking change for us somewhere, I believe our builds use something between SDL 2.0.4/2.0.8
