### ISSUE TITLE
Game doesn't update the view at full frame rate at 120/144hz

### ISSUE THREAD

**Issue by Modoh** [TurningWheel/Barony#594]
The game supports rendering at 120/144 fps, and you do see frames output at that rate if you use an overlay of some sort.   But moving the view around doesn't feel as smooth as it should, and capturing video of the game at high frame rates confirms it: many of the frames rendered are duplicates, and you only get around 60 actual unique frames per second.  

I understand that the game logic probably doesn't run at that high of a rate, but even getting the view/camera to update view angle at full rate would be an improvement, even if enemies and such were only updated at 60hz.

**Comment by SheridanR** [comment]
Camera movement has been drastically improved in our in-dev builds. Thanks for the ask :)
