### ISSUE TITLE
Ultrawide resolutions cause horizontal stretching of the UI

### ISSUE THREAD

**Issue by xubble** [TurningWheel/Barony#656]
This issue is present in v3.8.0 in the closed beta branch on Steam. 

It seems the new graphical UI stretches to fit the screen horizontally. This results in a stretched appearance for the UI when the game is set to a resolution that is not the standard 16:9 widescreen aspect ratio.

Here are a few example images of the graphical UI when the resolution is set to 5120x1440 (a 32:9 aspect ratio).

![image](https://user-images.githubusercontent.com/25457510/170849348-6b0408a8-73e0-45d3-8422-eeaf21240bff.png)

![image](https://user-images.githubusercontent.com/25457510/170849427-ffe6e4b8-3eb4-40e1-acea-014511063ad0.png)

![image](https://user-images.githubusercontent.com/25457510/170849441-e972f0db-e1a2-4d1b-ba00-1a1ec683b41a.png)

**Comment by SheridanR** [comment]
If you change the resolution through the settings menu on the `develop` branch, it will change the aspect ratio of the GUI. Maximizing or resizing the window does not do this however. The issue is that changing the aspect ratio requires resetting the UI state, so doing it every time the window size changes with the mouse is... disorienting. Maybe there should be a time delay before that happens so it still always corrects itself.

**Comment by SheridanR** [comment]
BTW in case you don't know, field-of-view is measured vertically, so very wide-screen monitors give you expanded horizontal FOV even if you don't change the setting. Just saying because I see you've maxed out the slider (:

**Comment by xubble** [comment]
Yep yep, was just checking the FOV slider to see if it behaved differently in the beta. 

I'll take a peek at the `develop` branch. Thanks for the speedy reply. 👍

**Comment by xubble** [comment]
I am reopening this ticket as the issue appears to be present as of 3.8.6. 

![image](https://user-images.githubusercontent.com/25457510/213326885-fb48ad45-f39e-46ec-9ba9-e9734e66f216.png)
![image](https://user-images.githubusercontent.com/25457510/213326897-6bda4d52-fbf8-44f4-8662-7741a20a6aae.png)

I would expect the GUI to at least remain in a 16:9 aspect ratio centered on the screen, but there is still this unnatural horizontal stretching of the GUI to fit the 32:9 screen resolution. Here is a (very quick) mockup and comparison of what I mean.

Current behavior:

![image](https://user-images.githubusercontent.com/25457510/213327012-7fb34f24-6e5d-4a98-9fbd-7068cd9af226.png)

Expected behavior:

![image](https://user-images.githubusercontent.com/25457510/213328045-06d7aabb-cad3-4749-94b0-1c3d868057d2.png)

The resolution is again set to 5120x1440, but the issue is apparent with any resolution that goes beyond the standard 16:9 aspect ratio.

**Comment by SheridanR** [comment]
I believe this has been fixed already in the `develop` branch, and in fact, macOS users already have the fix - Windows and Linux builds should get it in the next patch.
For now, as a workaround, you can use the /resizegui command in-game to change the size of the ui layer manually. I recommend these values:
`/resizegui 2560 720`

**Comment by xubble** [comment]
I was not aware of that command. But it does appear to resolve the stretched GUI. I appreciate the speedy response. Thank you!
