### ISSUE TITLE
Ambient sounds too loud

### ISSUE THREAD

**Issue by SheridanR** [TurningWheel/Barony#68]
A number of ambient sounds in the game are too loud (usually by having too many samples playing at a time, or at too high a volume).

Namely:

Water
Spike traps
Chests

Water is one of the bigger problems and actually can cause the music to stop in the swamps due to too many samples being played simultaneously.

The system that governs how frequently water samples play should also probably be rewritten so that those sounds play on a more predictable basis, as the rate is generally very random right now.

**Comment by addictgamer** [comment]
Possibly related: I've been noticing that sometimes music won't play. Usually combat music will, but shopkeepers, minotaurs, and level music sometimes won't play. Tileset transition levels...

**Comment by crkellen** [comment]
Is there a way to test this consistently? Is it known if this issue is present in OpenAL?

**Comment by WALLOFJUSTICE** [comment]
Addressed in V3.3.5
