### ISSUE TITLE
Audio Bug

### ISSUE THREAD

**Issue by randomnameforaccount** [TurningWheel/Barony#716]
I have a persistent audio bug that I have tried resolving through reinstallation, verification of game files, reinstall and update all audio drivers and headset drivers. I have uploaded an unlisted youtube video of the issue, and I will briefly describe it as well.

This audio sounds like it is distorted/bit crushed, it sounds like it is coming from a general location in the map as it will swap ears when you turn and get louder and quieter as you roam the level. It is on all levels, and only stops after I pause the game for a little bit, but then starts back up a couple of seconds after I unpause the game. It is very grating and makes it hard to try and play for an extended period as it simply persists the entire time.

Here is the video, https://youtu.be/Mm4BJS-T_Cg

**Comment by SheridanR** [comment]
I don't hear any problems in your YT video. You may be misidentifying the torch fire sound effect as some bit-crushed glitch noise. If it really bothers you, you can replace the sound effect in the `sounds` folder. But this is normal behavior.

**Comment by randomnameforaccount** [comment]
Yeah I figured that out as well, it sounds very grating, perhaps its also because of how loud and prevalent it is. I simply removed the fire file to fix this.
