### ISSUE TITLE
Shopkeepers sometimes don't respond to attacks

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#73]
Might be due to flooding his shop with followers? Related to minotaur bug?

**Comment by crkellen** [comment]
It seems the issue lies with distance. I haven't fully tracked it down yet, but distance seems to be a major part of it. I'll continue to track this one down and hopefully have it resolved soon.

**Comment by WALLOFJUSTICE** [comment]
Addressed in 457cbd69dd61c545d998b08af73a6ecfb4428905 for melee attacks on all friendlies
