### ISSUE TITLE
Restart after last player dies, game over screen appears after restart

### ISSUE THREAD

**Issue by Noobly-Walker** [TurningWheel/Barony#755]
In a multiplayer game, if the host restarts after the last player dies, but just before the game over screen appears, the game over screen will still appear even after the game has restarted. Clicking the Restart button on the game over screen after this point bugs out the host server, causing remote players to think the game is frozen, while the host is unable to get the players to move by bumping, and the players all have the same default face. This may be some form of desync.
![image](https://github.com/TurningWheel/Barony/assets/59349202/1b527cf6-8559-40a5-9674-5fafa255ffe9)

**Comment by SheridanR** [comment]
Hi there,

Your screenshot is of a version of the game that is 3 years old at this point, all of the UI has been remade. Can you retest in the latest version and see if it still happens?

**Comment by Noobly-Walker** [comment]
I'll try to get my friends back together in the next few days on the beta branch then.

**Comment by Noobly-Walker** [comment]
I attempted to replicate the bug on the Beta branch. I could not. Maybe it still exists, but I couldn't make it work.

**Comment by Noobly-Walker** [comment]
I will continue playing the latest build, as clearly, I've been missing out. If I encounter this issue again, I will reopen it.
