### ISSUE TITLE
ally repeat command while reading tutorial sign crashes game

### ISSUE THREAD

**Issue by xCeezyx** [TurningWheel/Barony#777]
Pressing the button to use the last ally command while reading a tutorial sign will instantly crash the game.
Only triggers if you have used an ally command before.

Steps to reproduce
Open Trial 7 tutorial
Recruit ally
Give ally Command
then Read any sign in the trial
Press q while the sign is on your screen

**Comment by WALLOFJUSTICE** [comment]
Thank you, fixed in 276bf24
