### ISSUE TITLE
[Linux] Missing Menu Text on Unchanged Build

### ISSUE THREAD

**Issue by Iceball457** [TurningWheel/Barony#781]
When building on linux, for linux, there's no text on the main menu, character creation screen, and pause menu. All other in-game text in the inventory and floating over players and enemies works just fine.
There's no mention of missing files or an inability to load some data, and this is the only text in game that is missing.
![image](https://github.com/TurningWheel/Barony/assets/41982718/3b80138a-f047-43cb-b11e-e64486686bbc)
Dropping the original executable into my TEST directory solves the problem, so I know that the issue is with the built executable, and not related to missing files

**Comment by WALLOFJUSTICE** [comment]
Hi, you'll need to use the lang/en.txt from the repo rather than the game files, we recently moved all main menu strings into that file but haven't released this publicly yet.

**Comment by WALLOFJUSTICE** [comment]
Just created tag V4.0.2 for the latest public release so feel free to use that.

**Comment by Iceball457** [comment]
Understood! Thank you for the quick response!
