### ISSUE TITLE
[Linux] [Steamworks] [4.0.2] Cannot build with steamworks

### ISSUE THREAD

**Issue by Iceball457** [TurningWheel/Barony#782]
This is probably another dumb dependency issue, but I have been beating my head on this for 12 hours and I want to go to bed.
`cmake -DCMAKE_BUILD_TYPE=Release -DFMOD_ENABLED=ON -DSTEAMWORKS_ENABLED=1 -DEOS_ENABLED=0 ..`
Iff the steamworks flag is set (the EOS flag is not set), I get an issue with the native file dialog
```
/usr/bin/ld: /home/frosti/repos/depend/nativefiledialog/release/lib/libnfd.a(nfd_gtk.o): undefined reference to symbol 'g_free'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libglib-2.0.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/barony.dir/build.make:2452: barony] Error 1
make[1]: *** [CMakeFiles/Makefile2:204: CMakeFiles/barony.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
I see that libglib-2.0.so doesn't seem to be linking properly, but I am not skilled enough to understand why or how to fix it

ps is there a chatroom I can join for non-issue modding help?

pps I can't apply labels here

**Comment by SheridanR** [comment]
Our discord has a channel for questions about working with the source.

I would try rebuilding libnfd from source. It's a very simple library with almost no dependencies so it should be easy enough:
[http](https://github.com/mlabbe/nativefiledialog)
