### ISSUE TITLE
Asset Replacement Bug: Player, Item, and Block Replacement by Green Orb

### ISSUE THREAD

**Issue by Rain-Rock-Man** [TurningWheel/Barony#786]
As stated in the title, my game has been corrupted by green orbs.

![20230912143039_1](https://github.com/TurningWheel/Barony/assets/144813105/e99125b7-0ab5-4090-bc40-66d16404faa2)
![20230912150205_1](https://github.com/TurningWheel/Barony/assets/144813105/0b193d60-22d0-40ce-bee4-85bf5a3e0858)

Similar to the images above. 

Things that have been replaced; Most equipable items in-game, some walls, door frames, Doors, Gates, turning crystals (used to open gates) some Mobs.

How did it happen?
I believe it happened due to a corrupted save.
1. I played the insectoid race with the Hunter Class, Collected the green orb, and quit the game while holding the item (Green orb).
2. I then joined a friend online and played through the game from start to end in two sessions. The first session finished after the 1st baron boss, We then took a break and came back to the second session beating the second and final boss. 
3. I then Loaded my Solo Insectoid save and noticed the problem with the corrupted orbs. I continued the game with the bug as I was near the end and didn't want to restart. I finished the game and noticed the orbs persisted even on the menu. I then started a new game and found the orb bug was still appearing, It also appeared in the tutorial zone.
4. Virfied Files, The game still had the green orb replacement asset bug.
5. Uninstalled and Reinstalled the game and the asset replacement bug still persists

I have not used any Mods for my game.

**Comment by SheridanR** [comment]
Hi there, use `/loadmodels` or delete the models.cache file in your game directory to resolve this problem.
