### ISSUE TITLE
Crash in Tinkering Tutorial

### ISSUE THREAD

**Issue by BlockedCircle** [TurningWheel/Barony#789]
I was reading a sign while doing the tinkering tutorial and pressed the Q button (default key bind for "repeat last command" for your followers) and the game crashed soon after. Went to do this a second time to ensure that it wasn't a one-time bug, with another nearby sign and it happened again. Might be minor, but thought I would mention this just in case it causes someone to crash in a real run!

**Comment by WALLOFJUSTICE** [comment]
Thanks, already corrected for next patch.

**Comment by BlockedCircle** [comment]
Oh, my bad if this was an already reported issue!

**Comment by WALLOFJUSTICE** [comment]
No problem. It wasn't being tracked here, I saw it on our Discord a little while back.
