### ISSUE TITLE
[2.0.5] Cursor keep moving up when gamepad is plugged in

### ISSUE THREAD

**Issue by HiPhish** [TurningWheel/Barony#80]
I have a gamepad (Logitech F310) and a flight stick (Logitech Extreme 3D Pro) plugged in at the same time. As long as the gamepad is plugged in the cursor keeps moving up, unless the right analog stick on the gamepad is being pushed halfway down, then the cursor stops. Having the flight stick plugged in has no adverse effect.

EDIT: The cursor keeps moving upwards of course.

**Comment by crkellen** [comment]
I cannot reproduce this on my end, but it sound exactly like the issue I have with Gamecube controllers.
Gamecube controllers have a C-Stick, which when the C-Stick gets stuck in a position for some time, will be constantly applying force in that direction. This is very noticeable in games like Super Smash Bros Melee as the pointer in menus will be moved by the C-Stick.

The way this was often fixed is by unplugging the controller, and rotating the C-Stick in a clean circular fashion (by clean I mean, only touching edges, full, even force in an outward direction as you rotate). This could possibly be the issue with your gamepad.

**Comment by HiPhish** [comment]
It's not happening any longer, must have been a one-time issue after updating or something, I hadn't tried it since filing this issue. I'm closing it then.
