### ISSUE TITLE
Fix game stutters upon doing something for the first time

### ISSUE THREAD

**Issue by koneko** [TurningWheel/Barony#834]
hello. when playing barony ive always had the issue of the game "randomly" stuttering whenever i first start playing and do an action (e.g. scrapping a torch, attacking a rat, etc) and i never found the fix. until (maybe) now. i think the problem with the stuttering comes from the game having to compile shaders upon said action, and then it keeps it loaded and doesnt stutter. i believe the fix for this is forcing the game to compile the shaders upon boot and keeping them there for 24 hours or something. [This](https://youtu.be/oG-H-IfXUqI?t=438) video goes over what someone else did in a game which has a similar graphical style to barony, so i hope this gets implemented one way or another. also i wish to note that the issue doesnt arise from bad hardware (i have the issue with an nvidia rtx 3060 gpu and ryzen 5800H cpu which is well above recommended specs) and trying the "fixes" suggested in the discord didnt solve the problem (turning off VSync, lowering resolution, preloading songs). hope this helps, since many other players have the same issue. cheers.

**Comment by SheridanR** [comment]
Barony uses its own game engine that compiles shaders on boot, not Godot.

**Comment by koneko** [comment]
I meant more as how someone would solve the shader compilation issue, i
would hope that sdl has a way to force compilation of shaders (or do what
the video did just for yourself).

**Comment by SheridanR** [comment]
There is no shader compilation issue. As I said, all shaders are compiled exactly once when the game starts. Also, SDL has nothing to do with shaders. If you're having performance troubles, it is something else.
