### ISSUE TITLE
Animated tiles with numbering 0-9 at the filename end count as swimming tiles

### ISSUE THREAD

**Issue by WALLOFJUSTICE** [TurningWheel/Barony#84]
Makes sense for the water/lava frames, but you swim in the glowing hell and citadel pillars if they are placed as ground tiles. Not an issue in the main maps as these animated blocks are for pillars, but affects mapmakers.

TODO: Merge the swimming checks into a common function, change the way we handle swimming tiles to only affect water/lava. Info is determined in init_game.cpp during the tiles.txt read. Stores the swimming result in animatedTiles[] which is referenced for subsequent swimming checks.

**Comment by crkellen** [comment]
This can likely be fixed with #144, as the addition of an Entity flag would allow for better handling of swimming checks. Commenting to implement later.

**Comment by addictgamer** [comment]
Fixed in #235
