### ISSUE TITLE
Feature Request [Ability to disable friendly fire during round]

### ISSUE THREAD

**Issue by shinysocks** [TurningWheel/Barony#857]
* This feature would be greatly appreciated to improve the ease of disabling friendly fire after a match has started.
* Alternatively, It would be convenient to have a visible button in the match start screen to remind players that friendly fire is enabled (my friends and I forget for nearly every match...)

**Comment by TurningWheel** [comment]
If you enter the Settings menu and go to the Game tab (accessible during a round) you can toggle friendly fire on and off (only available to the host)

**Comment by shinysocks** [comment]
Yes, it would just be nice if it was more clear when it was enabled..
