### ISSUE TITLE
error: failed to load image 'items/images/WoodenShield1.png

### ISSUE THREAD

**Issue by Adrien2002** [TurningWheel/Barony#88]
So I'm back with two platforms. I successfully built Barony on NetBSD and FreeBSD thanks to you.
I fetched the Windows version where I copied the binary of NetBSD on NetBSD and FreeBSD on FreeBSD.
When I run it, whatever which platform I am using, the game will crash and I'll have at the end of the log.txt :

> [13-46-25] loading items...
> '13-46-25] error: failed to load image 'items/images/WoodenShield1.png
> AL lib: (EE) alc_cleanup: 1 device not closed

I tried the game on Wine with FreeBSD and it perfectly works, no error message and it is the same downloaded file from GOG so the game is correctly downloaded

In case you want to see : 
$ sum -a SHA512 setup_barony_cursed_edition_2.1.0.3.exe
SHA512 (setup_barony_cursed_edition_2.1.0.3.exe) = 4011018d766508a046f3256b43c49fff9e35cfc93006bca6b2517dfd3db68a15eee1917966f385a77f93870c19593eeeb0c36544e90ea1a36542d2011434f1a8

On FreeBSD, I am on a laptop with a nVidia GPU (only one, no SLI) and I'm using the official driver
On NetBSD, I am on a desktop with a AMD GPU and I'm using the open source driver xf86-video-ati

If I precise why I'm not using SLI is because of this old topic on Steam
http://steamcommunity.com/app/371970/discussions/0/405691147592271367/
Where the guy was saying that he was using SLI and he changed a setting in his control panel then it worked and if I gave you the sha512 it is because another guy is saying that re-downloading the game fixed his problem which is not my case either.

Also, on the two systems, I have this in the very beginning of the log.txt file :

> [13-46-14] warning: syntax error in 'lang/en.txt':8
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':10
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':22
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':26
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':62
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':64
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':84
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':86
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':106
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':108
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':120
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':122
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':128
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':130
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':152
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':154
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':177
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':179
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':202
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':204
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':227
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':229
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':236
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':238
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':266
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':268
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':280
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':282
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':287
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':289
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':294
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':296
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':301
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':303
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':308
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':310
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':315
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':317
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':322
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':324
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':329
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':333
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':336
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':340
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':413
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':415
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':431
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':433
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':438
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':440
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':463
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':465
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':499
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':501
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':505
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':507
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':553
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':555
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':568
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':570
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':581
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':583
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':592
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':594
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':599
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':601
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':605
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':607
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':680
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':682
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':692
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':694
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':720
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':722
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':729
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':731
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':735
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':739
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':804
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':806
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':811
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':813
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':822
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':825
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':828
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':830
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':855
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':857
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':955
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':957
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':970
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':973
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':984
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':986
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1052
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1054
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1057
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1059
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1118
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1120
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1170
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1172
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1183
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1185
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1214
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1219
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1327
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1329
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1366
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1368
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1408
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1410
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1461
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1463
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1472
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1474
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1484
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1486
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1593
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1595
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1608
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1610
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1623
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1625
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1650
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1655
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1705
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1709
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1750
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1752
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1760
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1762
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1779
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1781
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1798
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1800
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1806
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1808
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1857
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1859
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1895
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1897
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1926
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':1928
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2157
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2159
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2262
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2264
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2303
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2305
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2321
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2323
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2660
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2662
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2665
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2667
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2698
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2700
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2703
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2705
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2706
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2707
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2708
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2709
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2710
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2711
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2712
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2713
>  bad syntax!
> [13-46-14] warning: syntax error in 'lang/en.txt':2714
>  bad syntax!
> [13-46-14] successfully loaded language file 'lang/en.txt'

Both are 64 bits architecture.

**Comment by SheridanR** [comment]
I don't recommend you use the Windows assets with a Unix-based binary as all the line endings in the text files will be incorrect (this is likely the source of all your warnings and errors). Can you try running the game with the linux assets instead?

**Comment by Adrien2002** [comment]
Oh... That was that simple, I didn't know there were differences between the GNU/Linux and Windows version. Indeed, it works http://i.imgur.com/O8gGcTd.jpg :)
Thank you, I hope this stupid mistake may help someone else so I didn't create that issue for nothing

**Comment by lheckemann** [comment]
The WoodenShield.png issue is probably due to NTFS ignoring filename case and linux/BSD filesystems not. This issue can be closed then I guess?

**Comment by Adrien2002** [comment]
The problem is solved, really, it works with the GNU/Linux datas and NetBSD/FreeBSD engine, I can play on the two systems.
No more trouble.

**Comment by lheckemann** [comment]
>This issue can be closed then I guess?

**Comment by Adrien2002** [comment]
Oh yes, sorry I didn't see
