### ISSUE TITLE
[2.0.5][Windows][Map Generation] Doors can replace walls of locked treasure rooms (bypassing lock)

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#99]
**ISSUE:**
On the first floor (past the starting floor 0), it is possible for certain layouts to replace walls that should not be replaced. In this instance shown below, a treasure room that requires you to flip a switch to open a gate (very very simple, often nothing to stop you from flipping it and grabbing loot), was accessible from the other side because a room with multiple doors had replaced the wall with empty space in front of a door.

**EXPECTED RESULT:**
Treasure rooms like this, which require access from either digging or a lever should not have their walls replaced by other rooms.

**STEPS TO REPRODUCE:**
This is a bit tricky to accurately reproduce, since I don't have a seed or anything. I have only seen this once, but it's clearly possible.

**ADDITIONAL INFO:**
![Image of the wall replaced by door](https://steamuserimages-a.akamaihd.net/ugc/854974606952390322/3D7434F0683CCD452FADBED8E87CD83C8E01BE4B/)
![Second Image from the other side](https://steamuserimages-a.akamaihd.net/ugc/854974606952391157/582FC310C3D84D1B94AC8E999B12B924FF576CAD/)

**Comment by SheridanR** [comment]
Not a bug... we're aware this can happen, but it's an intended side effect of the level gen process. If we didn't want it to happen we would've made the walls around the chest thicker.
